import json
from datetime import datetime
from pathlib import Path


class Report:
    def __init__(self, data: dict, name: str = "report"):
        self.data = data
        self.name = name
        self.timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.output_file = ""

    def generate(self):
        self._markdown_report()
        self._json_report()

    def _markdown_report(self):
        d = self.data
        target = d.get("target", "unknown")
        output_dir = Path("reports")
        output_dir.mkdir(exist_ok=True)
        self.output_file = str(output_dir / f"{self.name}_{self.timestamp}.md")

        lines = []
        lines.append(f"# Hunter-AI Report: {target}\n")
        lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        lines.append("---\n")

        # Recon
        recon = d.get("recon", {})
        lines.append("## 1. Reconnaissance\n")
        if recon.get("domains"):
            lines.append(f"**Subdomains found:** {len(recon['domains'])}\n")
            for dom in recon["domains"][:20]:
                lines.append(f"- {dom}\n")
        if recon.get("ips"):
            lines.append(f"\n**IPs resolved:** {', '.join(recon['ips'][:10])}\n")
        if recon.get("dns"):
            lines.append(f"\n**DNS Records:**\n")
            for k, v in recon["dns"].items():
                if v:
                    lines.append(f"- {k}: {', '.join(v[:5])}\n")
        if recon.get("whois"):
            lines.append(f"\n**WHOIS:**\n")
            for k, v in recon["whois"].items():
                lines.append(f"- {k}: {v}\n")

        # Scan
        scan = d.get("scan", {})
        lines.append("\n## 2. Port Scanning\n")
        if scan.get("open_ports"):
            lines.append(f"**Open ports:** {len(scan['open_ports'])}\n")
            lines.append("| Port | Protocol | Service |\n|------|----------|--------|\n")
            for p in scan["open_ports"][:30]:
                port = p.get("port", "?")
                proto = p.get("protocol", "tcp")
                svc = scan.get("services", {}).get(port, "?")
                lines.append(f"| {port} | {proto} | {svc} |\n")

        # Nuclei
        nuclei = scan.get("nuclei", [])
        if nuclei:
            lines.append(f"\n## 3. Vulnerability Scan (Nuclei)\n")
            lines.append(f"**Findings:** {len(nuclei)}\n\n")
            for n in nuclei[:15]:
                name = n.get("info", {}).get("name", n.get("template-id", "unknown"))
                severity = n.get("info", {}).get("severity", "unknown")
                matcher = n.get("matched-at", "")
                lines.append(f"- **[{severity.upper()}]** {name}\n  - `{matcher}`\n")

        # Web
        web = d.get("web", {})
        if web:
            lines.append("\n## 4. Web Testing\n")
            if web.get("directories"):
                lines.append(f"**Directories discovered:**\n")
                for d_path in web["directories"][:15]:
                    lines.append(f"- `{d_path}`\n")
            if web.get("tech_stack"):
                lines.append(f"\n**Technology stack:**\n")
                for tech in web["tech_stack"]:
                    lines.append(f"- {tech[:200]}\n")

        # Exploit
        exploit = d.get("exploit", {})
        if exploit:
            lines.append("\n## 5. Exploit Analysis\n")
            ai = exploit.get("ai_analysis", {})
            if ai:
                lines.append(f"**AI Recommendation:** {ai.get('reasoning', 'N/A')}\n")

        # Timeline
        lines.append("\n## 6. Timeline\n")
        for entry in d.get("timeline", []):
            lines.append(f"- {entry}\n")

        lines.append("\n---\n*Report generated by Hunter-AI*\n")
        Path(self.output_file).write_text("".join(lines))
        print(f"[+] Markdown report: {self.output_file}")

    def _json_report(self):
        output_dir = Path("reports")
        json_file = str(output_dir / f"{self.name}_{self.timestamp}.json")
        with open(json_file, "w") as f:
            json.dump(self.data, f, indent=2, default=str)
        print(f"[+] JSON report: {json_file}")
